### ISSUE TITLE
Fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by rob-blackbourn** [Kijewski/pyjson5#1]
Hi,

This looks interesting, but it wouldn't build on Ubuntu 16.04:

    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/home/BHDGSYSTEMATIC.COM/rblackbourn/Development/Scratch/python/json-example/.venv/include -I/usr/include/python3.7m -c pyjson5.cpp -o build/temp.linux-x86_64-3.7/pyjson5.o -std=c++11 -O2 -fPIC -ggdb1 -pipe -fomit-frame-pointer -fstack-protector-strong
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_datetime(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49259:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     __pyx_t_4 = PyUnicode_AsUTF8AndSize(__pyx_v_stringified, (&__pyx_v_length)); if (unlikely(__pyx_t_4 == ((char *)NULL))) __PYX_ERR(11, 257, __pyx_L1_error)
                                          ^
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_numeric(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49720:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     __pyx_t_7 = PyUnicode_AsUTF8AndSize(__pyx_v_formatter_string, (&__pyx_v_length)); if (unlikely(__pyx_t_7 == ((char *)NULL))) __PYX_ERR(11, 309, __pyx_L1_error)
                                        ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Looks like a simple cast problem?

**Comment by Kijewski** [comment]
Hi, thank you for your message!

Could you please test if the change in #2 fixes the problem for you?

**Comment by rob-blackbourn** [comment]
Hi. Still fails :(

```
Installing collected packages: pyjson5
  Running setup.py install for pyjson5 ... error
    Complete output from command /home/BHDGSYSTEMATIC.COM/rblackbourn/Development/Scratch/python/venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bokh09c4/pyjson5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-duystys6/install-record.txt --single-version-externally-managed --compile --install-headers /home/BHDGSYSTEMATIC.COM/rblackbourn/Development/Scratch/python/venv/include/site/python3.7/pyjson5:
    running install
    running build
    running build_ext
    building 'pyjson5' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/home/BHDGSYSTEMATIC.COM/rblackbourn/Development/Scratch/python/venv/include -I/usr/include/python3.7m -c pyjson5.cpp -o build/temp.linux-x86_64-3.7/pyjson5.o -std=c++11 -O2 -fPIC -ggdb1 -pipe -fomit-frame-pointer -fstack-protector-strong
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_datetime(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49259:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       __pyx_t_4 = PyUnicode_AsUTF8AndSize(__pyx_v_stringified, (&__pyx_v_length)); if (unlikely(__pyx_t_4 == ((char *)NULL))) __PYX_ERR(11, 257, __pyx_L1_error)
                                          ^
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_numeric(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49720:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
       __pyx_t_7 = PyUnicode_AsUTF8AndSize(__pyx_v_formatter_string, (&__pyx_v_length)); if (unlikely(__pyx_t_7 == ((char *)NULL))) __PYX_ERR(11, 309, __pyx_L1_error)
                                          ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
```

**Comment by Kijewski** [comment]
That's odd. I'll setup a VM with Ubuntu 16.04 later today (or maybe tomorrow) so I can debug the problem properly.

**Comment by emka** [comment]
I got the same error on Fedora 29, #2 fixed it.

**Comment by GuzTech** [comment]
I have the same issue in Arch Linux. Could you please merge #2 and release it?

I need it for a project I'm working on :)

**Comment by Kijewski** [comment]
I merged the pull request.
