### PR TITLE
Fix PyUnicode_AsUTF8AndSize() signature

### LINKED ISSUE #1: Fails to build on Ubuntu 16.04
Hi,

This looks interesting, but it wouldn't build on Ubuntu 16.04:

    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/home/BHDGSYSTEMATIC.COM/rblackbourn/Development/Scratch/python/json-example/.venv/include -I/usr/include/python3.7m -c pyjson5.cpp -o build/temp.linux-x86_64-3.7/pyjson5.o -std=c++11 -O2 -fPIC -ggdb1 -pipe -fomit-frame-pointer -fstack-protector-strong
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_datetime(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49259:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     __pyx_t_4 = PyUnicode_AsUTF8AndSize(__pyx_v_stringified, (&__pyx_v_length)); if (unlikely(__pyx_t_4 == ((char *)NULL))) __PYX_ERR(11, 257, __pyx_L1_error)
                                          ^
    pyjson5.cpp: In function ‘bool __pyx_f_7pyjson5__encode_numeric(__pyx_t_7pyjson5_WriterRef, PyObject*, __pyx_t_7pyjson5_EncType)’:
    pyjson5.cpp:49720:38: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     __pyx_t_7 = PyUnicode_AsUTF8AndSize(__pyx_v_formatter_string, (&__pyx_v_length)); if (unlikely(__pyx_t_7 == ((char *)NULL))) __PYX_ERR(11, 309, __pyx_L1_error)
                                        ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Looks like a simple cast problem?

### PR DESCRIPTION
**Pull request by Kijewski**
[`PyUnicode_AsUTF8AndSize()`][1] returns `const char*`, not `char*`.

Fixes #1.

  [1]: https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8AndSize

### CODE REVIEW

**Comment by Kijewski** [comment]
Merged
